### ISSUE TITLE
Don't cross feature

### ISSUE THREAD

**Issue by ImanMh** [lokku/jquery-nstslider#16]
Is it possible to prevent slider bullets crossing each other?

**Comment by ImanMh** [comment]
any updates on this one?

**Comment by darksmo** [comment]
yes

**Comment by darksmo** [comment]
I plan to add the `crossable_handles` option in the next version, but for now it would be cool if you can check the development version and let me know if it works for you. The option is documented in README.MD as can be seen on https://github.com/lokku/jquery-nstslider. You can clone the repository and use /dist/jquery.nstSlider.js or /dist/jquery.nstSlider.min.js directly as they've been updated.

[Reference commit](https://github.com/lokku/jquery-nstslider/commit/d5d879a3756ab80aa2ec2c93303b932e848e2344)

**Comment by ImanMh** [comment]
Thank you. That is what I was looking for how ever there is bug in my app right now which I'm not sure it's because of that last commit or not. When I drag the right handles over the other one they don't cross witch is pretty much expected, and when I drag the right handle back I can't move the left handle to left any more.
Do you have the same issue? I don't know if I could make it clear what the problem is or not.

**Comment by darksmo** [comment]
Working fine in the demo page under demo/ I have just added `crossable_handles = false` to the initialization. Hmm, can you give me more information?

- what browser are you using?
- how do you initialize the slider?

Maybe consider creating a jsfiddle that illustrates the case, you could fork and update [this one](http://jsfiddle.net/28YCS/9/) with your code to get it done quickly.

**Comment by ImanMh** [comment]
Yea you are right demo works perfect but It's wired and it seems like setting ```direction: rtl;``` on body and ```crossable_handles: false"``` on your config object will cause left handle to only be able to move to right!
I'm testing under chrome.

**Comment by darksmo** [comment]
Good point! fixing!

**Comment by darksmo** [comment]
Now should work

**Comment by ImanMh** [comment]
Thanks for your grate support dude!
We have a project on dead line and you just saved our asses on that.
