### ISSUE TITLE
Slider not working with Windows 8.1 in IE11 with zoom level greater than 100%

### ISSUE THREAD

**Issue by mojope** [lokku/jquery-nstslider#17]
Tested out your preview page inside IE11 with a zoom level at 200%. The sliderball keeps accelerating out of control compared to the mouse movement. This works fine inside both FF and Chrome. Did a check with a easyUI slider, which handles IE with zoom levels just fine.

This is especially troublesome for computers with high screen resolution that are using Windows 8.1's DPI settings to negate the screen size. Default there is to adjust the IE zoom levels from Windows.

From what I can understand, it has something to do with pageX not handling zoom levels in IE very well

**Comment by darksmo** [comment]
Fix coming soon ;) thanks for pointing it out!

**Comment by darksmo** [comment]
This should be fixed in v1.0.9 . Can you double check, so that I can close this issue?

**Comment by mojope** [comment]
Working perfectly!

Thank you for a quick reply.

**Comment by darksmo** [comment]
No problem, thanks for finding the bug! ;)
