### ISSUE TITLE
width of grip not calculated correctly (in certain cases..)

### ISSUE THREAD

**Issue by thinkMichel** [lokku/jquery-nstslider#18]
Hi,

great plugin! Am in the process of customising it with a different look and feel:

![image](https://cloud.githubusercontent.com/assets/813869/6885941/0cd08992-d62c-11e4-9bbf-e5c8fceb82cc.png)

And it seems that you use "width()" to get the current width of the grip. However i modified the grip to include a padding, but that 'breaks' the right grip, in that it will extend beyond the container.

I modified lines 192 and 204 (getLeftGripWidth, getRightGripWidth) to use outerWidth() instead of width(). Which does the trick. Any reason you use width (that may break something in the future) for me? 

have another issue, but will create a seperate issue for that :)

**Comment by darksmo** [comment]
Hi @thinkMichel , is there a way you could share your changes (including custom theme)? It would greatly help during the investigation of these open issues. You could send me an e-mail at darksmo@gmail.com if you don't want to share them publicly on GitHub.

**Comment by darksmo** [comment]
This will be in the next version: https://github.com/lokku/jquery-nstslider/commit/71f0204155ae80681ebc9b9c928a38ce7f478004
