### ISSUE TITLE
Not working with Safari mobile

### ISSUE THREAD

**Issue by cquilboss** [lokku/jquery-nstslider#21]
Hi,
The library is not working properly with Safari mobile (and other mobile browser).
To reproduce: open your demo page with a mobile browser (with no mouse) and drag the cursor.
In the console log you'll see an error like: 
*TypeError: undefined is not a function (evaluating 'e.preventDefault()')*

It's because you event e is empty (no mouse) on tablet or mobile.

Thanks

**Comment by mtmail** [comment]
Works fine for me on Safari mobile (iOS 8).
It doesn't work for me on Opera mini (10.0.1.90720 on iOS 8) though.

**Comment by cquilboss** [comment]
Just saw your commit to fix that, it works now. Thanks!

**Comment by darksmo** [comment]
@mtmail the slider was working on ipad too, but when connected to the debugger it was indeed showing the error mentioned in the issue. thanks @cquilboss for pointing at this!
