### ISSUE TITLE
bower.json doesn't contain main CSS file

### ISSUE THREAD

**Issue by SebastianTroc** [lokku/jquery-nstslider#25]
The grunt-wiredep auto-removes link to plugin's styles sheet, because of the absence of distribution CSS file path in the bower.json "main" section.
Was that intentional?
Do you think I can add it and make a pull request?

**Comment by darksmo** [comment]
Not intentional. Feel free to go ahead with a Pull request.

On Tuesday, 15 December 2015, Sebastian Troć <notifications@github.com>
wrote:

> The grunt-wiredep auto-removes link to plugin's styles sheet, because of
> the absence of distribution CSS file path in the bower.json "main" section.
> Was that intentional?
> Do you think I can add it and make a pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lokku/jquery-nstslider/issues/25>.
>


-- 
     Savio Dimatteo

**Comment by darksmo** [comment]
This was discussed, closing it. Feel free to re-open in case.

**Comment by SebastianTroc** [comment]
Honestly, I don't remember the issue so much, but I'll go with any pull request when I will find time for that. Thanks for the answer.
