### ISSUE TITLE
Init in hidden layer

### ISSUE THREAD

**Issue by mdss-single** [lokku/jquery-nstslider#27]
Hi.
I've a some problem.
If init slider into hidden layer (display:none) and .nstSlider has 100% width I've got wrong rightGrip position.

**Comment by darksmo** [comment]
Hi,

try calling the 'refresh' method after the slide is shown.

**Comment by obsergiu** [comment]
Thank you @darksmo, I suppose you could close the issue as this indeed fixes the problem.

**Comment by darksmo** [comment]
Closing :-)
