### ISSUE TITLE
Unable to get value from slider

### ISSUE THREAD

**Issue by ghost** [lokku/jquery-nstslider#34]
As far as I know this is not documented yet. I am unclear on how to get a value from the slider into my other functions to do calculations with. Apologies in advanced, I am new to web designing. Your implementation was a super solution to one of my problems of getting a pretty looking slider.

**Comment by darksmo** [comment]
Hello,

did you check the get_current_min_value and get_current_max_value from the README.md already?

**Comment by ghost** [comment]
Oh you're very much helpful! I shot those down in my head because I only had one slider. Two more question: do I need to parse this value to be able to pass it through one of my JS functions?
And am I able to pass the value as the slider moves into my functions?

**Comment by darksmo** [comment]
Please check Readme. First example in there shows that you can initialize with `value_changed_callback`, and you shouldn't need to parse the values.
